services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: toortaja
      POSTGRES_PASSWORD: toortaja
      POSTGRES_DB: toortaja
    ports:
      - "5433:5432"   # host:container
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
